export const EXPECTED_GUILD_COMMANDS = [
  { type: 1, name: 'admin' },
  { type: 1, name: 'civleaderboard' },
  { type: 1, name: 'draft' },
  { type: 1, name: 'help' },
  { type: 1, name: 'history' },
  { type: 2, name: 'Invite Player' },
  { type: 1, name: 'leaderboard' },
  { type: 1, name: 'leaders' },
  { type: 3, name: 'Match ID' },
  { type: 1, name: 'match' },
  { type: 1, name: 'mod' },
  { type: 1, name: 'ping' },
  { type: 2, name: 'Preview Rating' },
  { type: 1, name: 'rank' },
  { type: 1, name: 'settings' },
  { type: 1, name: 'stats' },
  { type: 1, name: 'tiers' },
  { type: 1, name: 'tournament' },
] as const
