import type { Leader } from './types.ts'

/** Curated competitive multiplayer tags keyed by leader ID */
export const leaderTagsById = {
  'america-abraham-lincoln': ['econ:production', 'win:domination', 'win:science', 'spike:mid', 'role:flex'],
  'america-teddy-roosevelt-bull-moose': ['win:science', 'win:culture', 'spike:mid', 'role:backline'],
  'america-teddy-roosevelt-rough-rider': ['win:domination', 'win:culture', 'spike:mid', 'role:flex', 'engine:trade', 'engine:diplo'],
  'arabia-saladin-vizier': ['econ:faith', 'win:science', 'spike:mid', 'role:backline', 'engine:religion'],
  'arabia-saladin-sultan': ['econ:faith', 'win:domination', 'win:science', 'spike:mid', 'role:frontline', 'engine:religion'],
  'australia-john-curtin': ['econ:production', 'win:science', 'win:culture', 'spike:mid', 'role:backline'],
  'aztec-montezuma': ['win:domination', 'win:culture', 'spike:early', 'role:frontline'],
  'babylon-hammurabi': ['econ:production', 'econ:food', 'win:science', 'win:domination', 'spike:early', 'role:flex'],
  'brazil-pedro-ii': ['win:culture', 'win:science', 'spike:mid', 'role:backline'],
  'byzantium-basil-ii': ['econ:faith', 'win:domination', 'win:science', 'spike:mid', 'role:frontline', 'engine:religion', 'engine:cavalry'],
  'byzantium-theodora': ['econ:faith', 'win:culture', 'win:domination', 'spike:mid', 'role:flex', 'engine:religion', 'engine:cavalry'],
  'canada-wilfrid-laurier': ['econ:food', 'econ:production', 'win:culture', 'win:science', 'spike:mid', 'role:backline'],
  'china-kublai-khan-china': ['econ:gold', 'win:science', 'win:culture', 'spike:mid', 'role:flex', 'engine:trade'],
  'china-qin-mandate-of-heaven': ['econ:production', 'econ:food', 'win:culture', 'win:science', 'spike:early', 'role:flex', 'engine:defense'],
  'china-qin-unifier': ['econ:production', 'econ:food', 'win:domination', 'win:culture', 'spike:early', 'role:frontline'],
  'china-wu-zetian': ['econ:faith', 'win:science', 'win:culture', 'spike:mid', 'role:flex'],
  'china-yongle': ['econ:gold', 'econ:food', 'win:science', 'win:culture', 'spike:late', 'role:backline'],
  'cree-poundmaker': ['econ:gold', 'econ:food', 'win:science', 'win:culture', 'spike:mid', 'role:flex', 'engine:trade'],
  'egypt-cleopatra-egyptian': ['econ:gold', 'econ:production', 'win:culture', 'win:science', 'spike:early', 'role:flex', 'engine:trade'],
  'egypt-cleopatra-ptolemaic': ['econ:production', 'win:science', 'win:domination', 'spike:mid', 'role:flex'],
  'egypt-ramses-ii': ['econ:production', 'win:culture', 'win:science', 'spike:mid', 'role:backline', 'engine:religion'],
  'england-eleanor-of-aquitaine-england': ['econ:production', 'econ:gold', 'win:culture', 'win:science', 'spike:late', 'role:backline', 'engine:naval'],
  'england-elizabeth-i': ['econ:gold', 'win:domination', 'win:science', 'spike:mid', 'role:flex', 'engine:trade', 'engine:naval'],
  'england-victoria-age-of-empire': ['win:domination', 'win:science', 'spike:mid', 'role:frontline', 'engine:naval'],
  'england-victoria-age-of-steam': ['econ:production', 'econ:gold', 'win:science', 'spike:late', 'role:backline', 'engine:naval'],
  'ethiopia-menelik-ii': ['econ:faith', 'win:science', 'win:culture', 'spike:mid', 'role:backline', 'engine:religion'],
  'france-catherine-de-medici-black-queen': ['win:domination', 'win:culture', 'spike:mid', 'role:flex'],
  'france-catherine-de-medici-magnificence': ['win:culture', 'win:science', 'spike:mid', 'role:backline'],
  'france-eleanor-of-aquitaine-france': ['econ:production', 'econ:gold', 'win:culture', 'win:science', 'spike:late', 'role:backline'],
  'gaul-ambiorix': ['econ:production', 'win:domination', 'win:culture', 'spike:early', 'role:frontline'],
  'gaul-vercingetorix': ['econ:production', 'win:culture', 'win:domination', 'spike:mid', 'role:flex', 'engine:defense', 'engine:diplo'],
  'georgia-tamar': ['econ:faith', 'win:domination', 'win:culture', 'spike:mid', 'role:flex', 'engine:religion', 'engine:diplo'],
  'germany-frederick-barbarossa': ['econ:production', 'win:domination', 'win:science', 'spike:mid', 'role:flex'],
  'germany-ludwig-ii': ['econ:production', 'win:culture', 'win:science', 'spike:mid', 'role:backline'],
  'gran-colombia-simon-bolivar': ['econ:production', 'econ:gold', 'win:domination', 'win:science', 'spike:mid', 'role:frontline', 'engine:cavalry'],
  'greece-gorgo': ['win:domination', 'win:culture', 'spike:early', 'role:frontline'],
  'greece-pericles': ['win:culture', 'win:science', 'spike:mid', 'role:backline', 'engine:diplo'],
  'hungary-matthias-corvinus': ['econ:gold', 'win:domination', 'win:science', 'spike:mid', 'role:flex', 'engine:cavalry', 'engine:diplo'],
  'inca-pachacuti': ['econ:food', 'econ:gold', 'win:science', 'win:culture', 'spike:mid', 'role:flex', 'engine:trade'],
  'india-chandragupta': ['econ:faith', 'win:domination', 'win:science', 'spike:mid', 'role:frontline', 'engine:religion'],
  'india-gandhi': ['econ:faith', 'win:science', 'win:culture', 'spike:mid', 'role:backline', 'engine:religion'],
  'indonesia-gitarja': ['econ:faith', 'win:domination', 'win:science', 'spike:mid', 'role:flex', 'engine:religion', 'engine:naval'],
  'japan-hojo-tokimune': ['econ:production', 'win:domination', 'win:culture', 'spike:mid', 'role:frontline', 'engine:naval'],
  'japan-tokugawa': ['win:science', 'win:culture', 'spike:mid', 'role:flex', 'engine:trade'],
  'khmer-jayavarman-vii': ['econ:faith', 'econ:food', 'win:science', 'win:culture', 'spike:mid', 'role:backline', 'engine:religion'],
  'kongo-mvemba-a-nzinga': ['econ:gold', 'econ:production', 'win:culture', 'win:domination', 'spike:mid', 'role:flex'],
  'kongo-nzinga-mbande': ['econ:gold', 'win:culture', 'win:science', 'spike:mid', 'role:backline', 'engine:trade'],
  'korea-sejong': ['econ:production', 'win:science', 'win:culture', 'spike:mid', 'role:backline'],
  'korea-seondeok': ['win:science', 'win:domination', 'spike:mid', 'role:flex'],
  'macedon-alexander': ['econ:production', 'win:domination', 'win:science', 'spike:early', 'role:frontline', 'engine:cavalry'],
  'macedon-olympias': ['econ:production', 'win:domination', 'win:science', 'spike:early', 'role:frontline'],
  'mali-mansa-musa': ['econ:gold', 'econ:faith', 'win:science', 'spike:mid', 'role:backline', 'engine:trade', 'engine:religion'],
  'mali-sundiata-keita': ['econ:gold', 'win:culture', 'win:science', 'spike:mid', 'role:backline', 'engine:trade'],
  'maori-kupe': ['win:culture', 'win:science', 'spike:early', 'role:flex', 'engine:naval'],
  'mapuche-lautaro': ['win:domination', 'win:culture', 'spike:mid', 'role:frontline', 'engine:cavalry'],
  'maya-lady-six-sky': ['win:science', 'win:domination', 'spike:early', 'role:flex', 'engine:defense'],
  'maya-te-k-inich-ii': ['win:domination', 'win:science', 'spike:mid', 'role:frontline'],
  'mongolia-genghis-khan': ['win:domination', 'win:science', 'spike:mid', 'role:frontline', 'engine:cavalry'],
  'mongolia-kublai-khan-mongolia': ['econ:gold', 'win:domination', 'win:science', 'spike:mid', 'role:flex', 'engine:trade', 'engine:cavalry'],
  'netherlands-wilhelmina': ['win:science', 'win:culture', 'spike:mid', 'role:flex', 'engine:trade', 'engine:naval'],
  'norway-harald-hardrada-varangian': ['econ:faith', 'win:domination', 'win:science', 'spike:mid', 'role:flex', 'engine:naval', 'engine:religion', 'engine:diplo'],
  'norway-harald-hardrada-konge': ['econ:production', 'win:domination', 'win:science', 'spike:mid', 'role:frontline', 'engine:naval'],
  'nubia-amanitore': ['econ:production', 'win:domination', 'win:science', 'spike:mid', 'role:flex'],
  'ottomans-suleiman-kanuni': ['win:domination', 'win:science', 'spike:mid', 'role:flex', 'engine:naval'],
  'ottomans-suleiman-muhtesem': ['win:science', 'win:domination', 'spike:mid', 'role:backline'],
  'persia-cyrus': ['win:domination', 'win:culture', 'spike:early', 'role:flex', 'engine:trade'],
  'persia-nader-shah': ['win:domination', 'win:science', 'spike:mid', 'role:frontline', 'engine:trade'],
  'phoenicia-dido': ['econ:production', 'win:science', 'win:culture', 'spike:early', 'role:flex', 'engine:trade', 'engine:naval'],
  'phoenicia-ahiram': ['econ:gold', 'econ:production', 'win:science', 'win:culture', 'spike:mid', 'role:backline', 'engine:trade', 'engine:naval'],
  'poland-jadwiga': ['econ:faith', 'econ:gold', 'win:culture', 'win:domination', 'spike:mid', 'role:flex', 'engine:religion', 'engine:cavalry'],
  'portugal-joao-iii': ['econ:gold', 'win:science', 'win:culture', 'spike:mid', 'role:backline', 'engine:trade', 'engine:naval'],
  'rome-julius-caesar': ['win:domination', 'win:science', 'spike:early', 'role:frontline'],
  'rome-trajan': ['econ:production', 'win:science', 'win:domination', 'spike:early', 'role:flex'],
  'russia-peter': ['econ:faith', 'win:science', 'win:culture', 'spike:mid', 'role:backline', 'engine:trade', 'engine:religion'],
  'scotland-robert-the-bruce': ['win:science', 'win:culture', 'spike:mid', 'role:flex', 'engine:defense'],
  'scythia-tomyris': ['win:domination', 'win:science', 'spike:early', 'role:frontline', 'engine:cavalry'],
  'spain-philip-ii': ['econ:faith', 'win:domination', 'win:culture', 'spike:mid', 'role:flex', 'engine:religion'],
  'sumeria-gilgamesh': ['econ:gold', 'win:domination', 'win:science', 'spike:early', 'role:frontline'],
  'swahili-al-hasan-ibn-sulaiman': ['econ:gold', 'win:science', 'win:culture', 'spike:mid', 'role:backline', 'engine:trade', 'engine:naval'],
  'sweden-kristina': ['win:culture', 'win:science', 'spike:late', 'role:backline'],
  'teotihuacan-spearthrower-owl': ['econ:gold', 'win:domination', 'win:science', 'spike:mid', 'role:flex', 'engine:trade', 'engine:diplo'],
  'thule-kiviuq': ['econ:food', 'win:domination', 'win:culture', 'spike:early', 'role:flex', 'engine:defense'],
  'tibet-trisong-detsen': ['econ:faith', 'win:domination', 'win:science', 'spike:mid', 'role:flex', 'engine:religion', 'engine:defense'],
  'vietnam-ba-trieu': ['win:domination', 'win:culture', 'spike:mid', 'role:frontline', 'engine:defense'],
  'zulu-shaka': ['win:domination', 'win:science', 'spike:mid', 'role:frontline'],
} as const satisfies Record<string, readonly string[]>

/** Apply curated tags to synced leaders in-place */
export function applyLeaderTags(leaders: Leader[]): void {
  for (const leader of leaders) {
    const tags = leaderTagsById[leader.id as keyof typeof leaderTagsById]
    leader.tags = tags ? [...tags] : []
  }
}
