import iconSet from '@iconify-json/fluent-emoji/icons.json'
import emojiData from 'unicode-emoji-json'
import { mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const DEFAULT_TOURNAMENT_ID = 'ven2G6d8ln'
const OUTPUT_PATH = fileURLToPath(new URL('../src/constants/tournament-emoji-icons.ts', import.meta.url))
const WRANGLER_CONFIG = fileURLToPath(new URL('../wrangler.ppl.jsonc', import.meta.url))
const SKIN_TONE_SUFFIX_BY_MODIFIER: Record<string, string> = {
  '\u{1F3FB}': 'light',
  '\u{1F3FC}': 'medium-light',
  '\u{1F3FD}': 'medium',
  '\u{1F3FE}': 'medium-dark',
  '\u{1F3FF}': 'dark',
}
const SKIN_TONE_MODIFIER_PATTERN = /[\u{1F3FB}-\u{1F3FF}]/gu
const VARIATION_SELECTOR_16 = '\uFE0F'
const unicodeEmojiData = emojiData as Record<string, UnicodeEmojiEntry>
const graphemeSegmenter = typeof Intl.Segmenter === 'function'
  ? new Intl.Segmenter(undefined, { granularity: 'grapheme' })
  : null

interface D1Result<T> { results?: T[], success?: boolean, errors?: unknown[] }
interface NameRow { display_name: string }
interface UnicodeEmojiEntry { name: string, slug: string }
interface EmojiMetadata { entry: UnicodeEmojiEntry, toneSuffix: string | null }
interface IconData { width: number, height: number, body: string }
interface IconifyIconData { width?: number, height?: number, body?: string, parent?: string, hFlip?: boolean, vFlip?: boolean, rotate?: number }

const sourceTexts = await collectSourceTexts()
const emojis = collectEmojiCandidates(sourceTexts)
const sortedEmojis = [...emojis].sort()
const unmapped = new Map<string, string>()

const iconEntries = sortedEmojis.map((emoji) => {
  const metadata = resolveEmojiMetadata(emoji)
  if (!metadata) {
    unmapped.set(emoji, 'missing Unicode emoji metadata')
    return null
  }

  const iconName = resolveFluentIconName(metadata)
  if (!iconName) {
    unmapped.set(emoji, `no fluent-emoji icon for ${metadata.entry.slug}`)
    return null
  }

  const icon = resolveFluentIcon(iconName)
  if (!icon) throw new Error(`Missing fluent-emoji icon: ${iconName}`)
  return [emoji, icon, iconName] as const
})

if (unmapped.size > 0) {
  throw new Error([
    'Unable to map tournament emoji to Fluent Emoji icons:',
    ...[...unmapped].sort().map(([emoji, reason]) => `- ${emoji}: ${reason}`),
    'Update unicode-emoji-json/@iconify-json/fluent-emoji or add a generic name transform.',
  ].join('\n'))
}

const icons = Object.fromEntries(iconEntries.flatMap(entry => entry ? [[entry[0], entry[1]]] : []))
const iconNames = Object.fromEntries(iconEntries.flatMap(entry => entry ? [[entry[0], entry[2]]] : []))

await mkdir(dirname(OUTPUT_PATH), { recursive: true })
await Bun.write(OUTPUT_PATH, `// Generated by apps/bot/scripts/generate-tournament-emoji-icons.ts. Do not edit manually.
export interface TournamentEmojiIcon {
  width: number
  height: number
  body: string
}

export const TOURNAMENT_EMOJI_ICONS = ${JSON.stringify(icons, null, 2)} as const satisfies Record<string, TournamentEmojiIcon>
`)

console.log(JSON.stringify({ outputPath: OUTPUT_PATH, emojis: sortedEmojis, iconNames }, null, 2))

async function collectSourceTexts(): Promise<string[]> {
  const texts: string[] = []
  const d1TournamentId = argValue('--d1-tournament-id') ?? (hasFlag('--ppl-current') ? DEFAULT_TOURNAMENT_ID : null)
  if (d1TournamentId) {
    texts.push(...runD1<NameRow>(`
      SELECT display_name
      FROM tournament_players
      WHERE tournament_id = ${sqlString(d1TournamentId)} AND confirmed = 1;
    `).map(row => row.display_name))
  }

  const emojiArgs = argValues('--emoji')
  texts.push(...emojiArgs)

  const files = positionalArgs().filter(arg => !arg.startsWith('--'))
  for (const file of files) texts.push(await Bun.file(file).text())

  if (texts.length === 0 && !hasFlag('--allow-empty')) {
    const existingEmojis = await collectExistingOutputEmojis()
    texts.push(...existingEmojis)
    if (existingEmojis.length === 0) {
      throw new Error('No emoji sources found. Pass --d1-tournament-id <id>, --emoji <emoji>, one or more CSV/text files, or --allow-empty.')
    }
  }

  return texts
}

async function collectExistingOutputEmojis(): Promise<string[]> {
  const file = Bun.file(OUTPUT_PATH)
  if (!await file.exists()) return []
  const module = await import(`${pathToFileURL(OUTPUT_PATH).href}?cache=${Date.now()}`).catch(() => null) as { TOURNAMENT_EMOJI_ICONS?: Record<string, unknown> } | null
  return Object.keys(module?.TOURNAMENT_EMOJI_ICONS ?? {})
}

function collectEmojiCandidates(texts: string[]): Set<string> {
  const result = new Set<string>()
  for (const text of texts) {
    for (const grapheme of splitGraphemes(text)) {
      if (isEmojiCandidate(grapheme)) result.add(grapheme)
    }
  }
  return result
}

function splitGraphemes(value: string): string[] {
  if (!graphemeSegmenter) return Array.from(value)
  return [...graphemeSegmenter.segment(value)].map(segment => segment.segment)
}

function isEmojiCandidate(value: string): boolean {
  if (resolveEmojiMetadata(value)) return true
  return /\p{Extended_Pictographic}|\p{Regional_Indicator}|\u20E3/u.test(value)
}

function resolveEmojiMetadata(value: string): EmojiMetadata | null {
  const direct = unicodeEmojiData[value]
  if (direct) return { entry: direct, toneSuffix: null }

  const withoutTone = value.replace(SKIN_TONE_MODIFIER_PATTERN, '')
  const toneSuffix = resolveSkinToneSuffix(value)
  if (toneSuffix && withoutTone !== value) {
    const toned = findUnicodeEmojiEntry(withoutTone)
    if (toned) return { entry: toned, toneSuffix }
  }

  const entry = findUnicodeEmojiEntry(value)
  return entry ? { entry, toneSuffix: null } : null
}

function findUnicodeEmojiEntry(value: string): UnicodeEmojiEntry | null {
  const candidates = [
    value,
    value.replaceAll(VARIATION_SELECTOR_16, ''),
    addEmojiVariationSelectors(value),
  ]
  for (const candidate of unique(candidates)) {
    const entry = unicodeEmojiData[candidate]
    if (entry) return entry
  }
  return null
}

function addEmojiVariationSelectors(value: string): string {
  return splitGraphemes(value).map((grapheme) => {
    if (grapheme.includes(VARIATION_SELECTOR_16)) return grapheme
    return /\p{Extended_Pictographic}/u.test(grapheme) ? `${grapheme}${VARIATION_SELECTOR_16}` : grapheme
  }).join('')
}

function resolveSkinToneSuffix(value: string): string | null {
  for (const modifier of value.match(SKIN_TONE_MODIFIER_PATTERN) ?? []) {
    const suffix = SKIN_TONE_SUFFIX_BY_MODIFIER[modifier]
    if (suffix) return suffix
  }
  return null
}

function resolveFluentIconName(metadata: EmojiMetadata): string | null {
  for (const candidate of buildFluentIconNameCandidates(metadata)) {
    if (hasFluentIcon(candidate)) return candidate
  }
  return null
}

function buildFluentIconNameCandidates(metadata: EmojiMetadata): string[] {
  const baseCandidates = unique([
    toIconName(metadata.entry.slug),
    toIconName(metadata.entry.name),
  ].flatMap(name => expandIconNameVariants(name)))

  if (!metadata.toneSuffix) return baseCandidates
  return unique(baseCandidates.flatMap(name => [`${name}-${metadata.toneSuffix}`, name]))
}

function expandIconNameVariants(name: string): string[] {
  const names = new Set<string>([name])
  for (const candidate of [...names]) names.add(candidate.replace(/blond/g, 'blonde'))
  for (const candidate of [...names]) names.add(candidate.replace(/-o-clock/g, '-oclock'))
  for (const candidate of [...names]) {
    const personSuffix = candidate.match(/^(.*)-(person|man|woman)$/)
    if (personSuffix) names.add(`${personSuffix[2]}-${personSuffix[1]}`)
    names.add(`person-${candidate}`)
    names.add(`man-${candidate}`)
    names.add(`woman-${candidate}`)
  }
  return [...names]
}

function toIconName(value: string): string {
  return value
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function hasFluentIcon(name: string): boolean {
  return name in iconSet.icons || name in (iconSet.aliases ?? {})
}

function resolveFluentIcon(name: string, seen = new Set<string>()): IconData | null {
  if (seen.has(name)) throw new Error(`Circular fluent-emoji alias: ${[...seen, name].join(' -> ')}`)
  seen.add(name)

  const icon = iconSet.icons[name] as IconifyIconData | undefined
  if (icon?.body) return normalizeIconData(icon)

  const alias = (iconSet.aliases ?? {})[name] as IconifyIconData | undefined
  if (!alias?.parent) return null

  const parent = resolveFluentIcon(alias.parent, seen)
  if (!parent) return null
  return {
    width: alias.width ?? parent.width,
    height: alias.height ?? parent.height,
    body: applyIconTransform(parent.body, alias, parent.width, parent.height),
  }
}

function normalizeIconData(icon: IconifyIconData): IconData {
  return {
    width: icon.width ?? iconSet.width ?? 32,
    height: icon.height ?? iconSet.height ?? 32,
    body: applyIconTransform(icon.body ?? '', icon, icon.width ?? iconSet.width ?? 32, icon.height ?? iconSet.height ?? 32),
  }
}

function applyIconTransform(body: string, icon: IconifyIconData, width: number, height: number): string {
  const hFlip = icon.hFlip === true
  const vFlip = icon.vFlip === true
  if (!hFlip && !vFlip) return body
  const x = hFlip ? width : 0
  const y = vFlip ? height : 0
  return `<g transform="translate(${x} ${y}) scale(${hFlip ? -1 : 1} ${vFlip ? -1 : 1})">${body}</g>`
}

function unique<T>(values: Iterable<T>): T[] {
  return [...new Set(values)]
}

function runD1<T>(sql: string): T[] {
  const command = sql.replace(/\s+/g, ' ').trim()
  const proc = Bun.spawnSync(['bun', 'x', 'wrangler', 'd1', 'execute', 'civup', '--remote', '--config', WRANGLER_CONFIG, '--json', '--command', command], { stdout: 'pipe', stderr: 'pipe' })
  const stdout = new TextDecoder().decode(proc.stdout).trim()
  const stderr = new TextDecoder().decode(proc.stderr).trim()
  if (proc.exitCode !== 0) throw new Error(stderr || stdout || `wrangler exited ${proc.exitCode}`)
  const payload = JSON.parse(stdout) as D1Result<T>[]
  const failed = payload.find(result => result.success === false)
  if (failed) throw new Error(JSON.stringify(failed.errors ?? failed))
  return payload[0]?.results ?? []
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function hasFlag(name: string): boolean {
  return process.argv.includes(name)
}

function argValue(name: string): string | null {
  return argValues(name)[0] ?? null
}

function argValues(name: string): string[] {
  const values: string[] = []
  const prefix = `${name}=`
  for (let index = 2; index < process.argv.length; index++) {
    const arg = process.argv[index]!
    if (arg.startsWith(prefix)) values.push(arg.slice(prefix.length))
    else if (arg === name && process.argv[index + 1]) values.push(process.argv[++index]!)
  }
  return values
}

function positionalArgs(): string[] {
  const result: string[] = []
  for (let index = 2; index < process.argv.length; index++) {
    const arg = process.argv[index]!
    if (arg.startsWith('--')) {
      if (!arg.includes('=') && process.argv[index + 1] && !process.argv[index + 1]!.startsWith('--')) index += 1
      continue
    }
    result.push(arg)
  }
  return result
}
