import { sql } from 'drizzle-orm'
import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'

export const autosaveUploads = sqliteTable('autosave_uploads', {
  id: text('id').primaryKey(),
  uploadedAt: integer('uploaded_at', { mode: 'number' }).notNull(),
  uploaderUserId: text('uploader_user_id').notNull(),
  uploaderDisplayName: text('uploader_display_name'),
  channelId: text('channel_id'),
  matchId: text('match_id'),
  fileName: text('file_name').notNull(),
  fileSizeBytes: integer('file_size_bytes', { mode: 'number' }).notNull(),
  r2Key: text('r2_key').notNull(),
  multipartUploadId: text('multipart_upload_id'),
  multipartOperationId: text('multipart_operation_id'),
  multipartStateUpdatedAt: integer('multipart_state_updated_at', { mode: 'number' }),
  etag: text('etag'),
  status: text('status').notNull().default('uploaded'),
  downloadCount: integer('download_count', { mode: 'number' }).notNull().default(0),
  parseStatus: text('parse_status').notNull().default('pending'),
  parseError: text('parse_error'),
  saveCount: integer('save_count', { mode: 'number' }),
  maxTurn: integer('max_turn', { mode: 'number' }),
  latestSaveName: text('latest_save_name'),
  playerCount: integer('player_count', { mode: 'number' }),
  gameMode: text('game_mode'),
  leadersJson: text('leaders_json'),
  civsJson: text('civs_json'),
  playersJson: text('players_json'),
  mapFile: text('map_file'),
  modsJson: text('mods_json'),
  bbgDetected: integer('bbg_detected', { mode: 'boolean' }).notNull().default(false),
  bbgTitle: text('bbg_title'),
  bbgVersion: text('bbg_version'),
  notes: text('notes'),
}, table => [
  uniqueIndex('autosave_uploads_r2_key_idx').on(table.r2Key),
  index('autosave_uploads_uploaded_at_idx').on(table.uploadedAt),
  index('autosave_uploads_uploader_idx').on(table.uploaderUserId, table.uploadedAt),
  index('autosave_uploads_game_mode_idx').on(table.gameMode),
  index('autosave_uploads_bbg_version_idx').on(table.bbgVersion),
  index('autosave_uploads_parse_status_idx').on(table.parseStatus, table.uploadedAt),
  index('autosave_uploads_cleanup_state_idx').on(table.status, table.multipartStateUpdatedAt),
  uniqueIndex('autosave_uploads_active_uploader_idx')
    .on(table.uploaderUserId)
    .where(sql`${table.status} IN ('initializing','pending_upload','completing','cleanup_pending','cleaning')`),
])
