import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { Database } from 'bun:sqlite'

const CRC32_TABLE = createCrc32Table()

const CORE_TYPES = [
  'YIELD_FOOD',
  'YIELD_PRODUCTION',
  'YIELD_GOLD',
  'YIELD_SCIENCE',
  'YIELD_CULTURE',
  'YIELD_FAITH',
] as const

const CORE_TYPE_NAMES = new Map(CORE_TYPES.map(type => [civHash(type), type]))

export const CIV_REPLAY_DEDICATION_TYPE_NAMES = [
  'COMMEMORATION_ESPIONAGE',
  'COMMEMORATION_INDUSTRIAL',
  'COMMEMORATION_INFRASTRUCTURE',
  'COMMEMORATION_MILITARY',
  'COMMEMORATION_AERONAUTICAL',
  'COMMEMORATION_SCIENTIFIC',
  'COMMEMORATION_EXPLORATION',
  'COMMEMORATION_CULTURAL',
  'COMMEMORATION_TOURISM',
  'COMMEMORATION_AUTOMATON',
  'COMMEMORATION_ECONOMIC',
  'COMMEMORATION_RELIGIOUS',
] as const

export const CIV_REPLAY_DEDICATION_DISPLAY_NAMES: Record<(typeof CIV_REPLAY_DEDICATION_TYPE_NAMES)[number], string> = {
  COMMEMORATION_AERONAUTICAL: 'Sky and Stars',
  COMMEMORATION_AUTOMATON: 'Automaton Warfare',
  COMMEMORATION_CULTURAL: 'Pen, Brush, and Voice',
  COMMEMORATION_ECONOMIC: 'Reform the Coinage',
  COMMEMORATION_ESPIONAGE: 'Bodyguard of Lies',
  COMMEMORATION_EXPLORATION: 'Hic Sunt Dracones',
  COMMEMORATION_INDUSTRIAL: 'Heartbeat of Steam',
  COMMEMORATION_INFRASTRUCTURE: 'Monumentality',
  COMMEMORATION_MILITARY: 'To Arms!',
  COMMEMORATION_RELIGIOUS: 'Drums of War',
  COMMEMORATION_SCIENTIFIC: 'Free Inquiry',
  COMMEMORATION_TOURISM: 'Wish You Were Here',
}

const CIV_REPLAY_DEDICATION_DISPLAY_NAMES_BY_HASH = new Map(
  CIV_REPLAY_DEDICATION_TYPE_NAMES.map(type => [civHash(type), CIV_REPLAY_DEDICATION_DISPLAY_NAMES[type]]),
)

const STATIC_TYPE_NAMES = [
  ...CORE_TYPES,
  ...CIV_REPLAY_DEDICATION_TYPE_NAMES,
  'TECH_MINING',
  'TECH_POTTERY',
  'TECH_ANIMAL_HUSBANDRY',
  'TECH_SAILING',
  'TECH_ASTROLOGY',
  'TECH_ARCHERY',
  'TECH_IRRIGATION',
  'TECH_WRITING',
  'TECH_MASONRY',
  'TECH_BRONZE_WORKING',
  'TECH_THE_WHEEL',
  'TECH_CELESTIAL_NAVIGATION',
  'TECH_CURRENCY',
  'TECH_HORSEBACK_RIDING',
  'TECH_IRON_WORKING',
  'TECH_SHIPBUILDING',
  'TECH_MATHEMATICS',
  'TECH_CONSTRUCTION',
  'TECH_ENGINEERING',
  'TECH_APPRENTICESHIP',
  'TECH_MACHINERY',
  'TECH_EDUCATION',
  'TECH_MILITARY_TACTICS',
  'TECH_CASTLES',
  'TECH_STIRRUPS',
  'TECH_CARTOGRAPHY',
  'TECH_MASS_PRODUCTION',
  'TECH_BANKING',
  'TECH_GUNPOWDER',
  'TECH_PRINTING',
  'TECH_SQUARE_RIGGING',
  'TECH_ASTRONOMY',
  'TECH_METAL_CASTING',
  'TECH_SIEGE_TACTICS',
  'TECH_INDUSTRIALIZATION',
  'TECH_SCIENTIFIC_THEORY',
  'TECH_BUTTRESS',
  'CIVIC_CODE_OF_LAWS',
  'CIVIC_FOREIGN_TRADE',
  'CIVIC_CRAFTSMANSHIP',
  'CIVIC_EARLY_EMPIRE',
  'CIVIC_STATE_WORKFORCE',
  'CIVIC_MYSTICISM',
  'CIVIC_GAMES_RECREATION',
  'CIVIC_POLITICAL_PHILOSOPHY',
  'CIVIC_DRAMA_POETRY',
  'CIVIC_MILITARY_TRADITION',
  'CIVIC_DEFENSIVE_TACTICS',
  'CIVIC_RECORDED_HISTORY',
  'CIVIC_THEOLOGY',
  'CIVIC_MILITARY_TRAINING',
  'CIVIC_FEUDALISM',
  'CIVIC_CIVIL_SERVICE',
  'CIVIC_MERCENARIES',
  'CIVIC_MEDIEVAL_FAIRES',
  'CIVIC_GUILDS',
  'CIVIC_EXPLORATION',
  'CIVIC_HUMANISM',
  'CIVIC_DIPLOMATIC_SERVICE',
  'CIVIC_REFORMED_CHURCH',
  'CIVIC_MERCANTILISM',
  'CIVIC_THE_ENLIGHTENMENT',
  'CIVIC_DIVINE_RIGHT',
  'CIVIC_CIVIL_ENGINEERING',
  'CIVIC_NAVAL_TRADITION',
  'CIVIC_OPERA_BALLET',
  'CIVIC_NATIONALISM',
  'CIVIC_URBANIZATION',
  'CIVIC_COLONIALISM',
  'GOVERNMENT_CHIEFDOM',
  'GOVERNMENT_AUTOCRACY',
  'GOVERNMENT_OLIGARCHY',
  'GOVERNMENT_CLASSICAL_REPUBLIC',
  'GOVERNMENT_MONARCHY',
  'GOVERNMENT_THEOCRACY',
  'GOVERNMENT_MERCHANT_REPUBLIC',
  'GOVERNMENT_FASCISM',
  'GOVERNMENT_COMMUNISM',
  'GOVERNMENT_DEMOCRACY',
  'GOVERNMENT_SYNTHETIC_TECHNOCRACY',
  'GOVERNMENT_CORPORATE_LIBERTARIANISM',
  'GOVERNMENT_DIGITAL_DEMOCRACY',
  'POLICY_DISCIPLINE',
  'POLICY_SURVEY',
  'POLICY_GOD_KING',
  'POLICY_URBAN_PLANNING',
  'POLICY_AGOGE',
  'POLICY_CARAVANSERIES',
  'POLICY_CORVEE',
  'POLICY_ILKUM',
  'POLICY_LAND_SURVEYORS',
  'POLICY_MARITIME_INDUSTRIES',
  'POLICY_MANEUVER',
  'POLICY_REVELATION',
  'POLICY_COLONIZATION',
  'POLICY_INSULAE',
  'POLICY_LIMITANEI',
  'POLICY_CONSCRIPTION',
  'POLICY_NATURAL_PHILOSOPHY',
  'POLICY_SCRIPTURE',
  'POLICY_NAVAL_INFRASTRUCTURE',
  'POLICY_INSPIRATION',
  'POLICY_LITERARY_TRADITION',
  'POLICY_DIPLOMATIC_LEAGUE',
  'POLICY_CHARISMATIC_LEADER',
  'POLICY_RAID',
  'POLICY_VETERANCY',
  'POLICY_EQUESTRIAN_ORDERS',
  'POLICY_FEUDAL_CONTRACT',
  'POLICY_SERFDOM',
  'POLICY_MERCHANT_CONFEDERATION',
  'POLICY_GOV_AUTOCRACY',
  'POLICY_CRAFTSMEN',
  'POLICY_GOTHIC_ARCHITECTURE',
  'POLICY_TRADE_CONFEDERATION',
  'POLICY_INVENTION',
  'POLICY_PROFESSIONAL_ARMY',
  'POLICY_WISSELBANKEN',
  'POLICY_PUBLIC_WORKS',
  'POLICY_MASTER_ARTISANS',
  'POLICY_SKYSCRAPERS',
  'GOODYHUT_SCIENCE',
  'GOODYHUT_CULTURE',
  'GOODYHUT_GOLD',
  'GOODYHUT_FAITH',
  'GOODYHUT_MILITARY',
  'GOODYHUT_SURVIVORS',
  'GOODYHUT_SCOUTS',
  'GOODYHUT_EXPERIENCE',
  'GOODYHUT_HEALING',
  'GOODYHUT_RELIC',
  'COMMMEMORATION_ESPIONAGE',
  'COMMMEMORATION_INDUSTRIAL',
  'COMMMEMORATION_INFRASTRUCTURE',
  'COMMMEMORATION_MILITARY',
  'COMMMEMORATION_AERONAUTICAL',
  'COMMMEMORATION_SCIENTIFIC',
  'COMMMEMORATION_EXPLORATION',
  'COMMMEMORATION_CULTURAL',
  'COMMMEMORATION_TOURISM',
  'COMMMEMORATION_AUTOMATON',
  'COMMMEMORATION_ECONOMIC',
  'COMMMEMORATION_RELIGIOUS',
  'UNIT_SETTLER',
  'UNIT_BUILDER',
  'UNIT_TRADER',
  'UNIT_SCOUT',
  'UNIT_WARRIOR',
  'UNIT_SLINGER',
  'UNIT_ARCHER',
  'UNIT_SPEARMAN',
  'UNIT_HEAVY_CHARIOT',
  'UNIT_HORSEMAN',
  'UNIT_SWORDSMAN',
  'UNIT_CATAPULT',
  'UNIT_GALLEY',
  'UNIT_QUADRIREME',
  'UNIT_BATTERING_RAM',
  'UNIT_SIEGE_TOWER',
  'UNIT_CROSSBOWMAN',
  'UNIT_KNIGHT',
  'UNIT_MAN_AT_ARMS',
  'UNIT_TREBUCHET',
  'UNIT_SPY',
  'UNIT_GREAT_MERCHANT',
  'UNIT_GREAT_SCIENTIST',
  'UNIT_GREAT_ENGINEER',
  'UNIT_MISSIONARY',
  'UNIT_APOSTLE',
  'UNIT_INQUISITOR',
  'BUILDING_MONUMENT',
  'BUILDING_GRANARY',
  'BUILDING_WATER_MILL',
  'BUILDING_LIBRARY',
  'BUILDING_SHRINE',
  'BUILDING_TEMPLE',
  'BUILDING_MARKET',
  'BUILDING_LIGHTHOUSE',
  'BUILDING_BARRACKS',
  'BUILDING_STABLE',
  'BUILDING_ARENA',
  'BUILDING_AMPHITHEATER',
  'BUILDING_WORKSHOP',
  'BUILDING_UNIVERSITY',
  'BUILDING_BANK',
  'BUILDING_ARMORY',
  'BUILDING_WALLS',
  'BUILDING_CASTLE',
  'BUILDING_GOV_WIDE',
  'BUILDING_GOV_CITYSTATES',
  'BUILDING_FACTORY',
  'BUILDING_COAL_POWER_PLANT',
  'BUILDING_CASA_DE_CONTRATACION',
  'BUILDING_MACHU_PICCHU',
  'BUILDING_POTALA_PALACE',
  'BUILDING_GREAT_LIBRARY',
  'BUILDING_PYRAMIDS',
  'BUILDING_FORBIDDEN_CITY',
  'BUILDING_JEBEL_BARKAL',
  'BUILDING_ANGKOR_WAT',
  'BUILDING_CONSULATE',
  'BUILDING_CHANCERY',
  'DISTRICT_CITY_CENTER',
  'DISTRICT_CAMPUS',
  'DISTRICT_HOLY_SITE',
  'DISTRICT_ENCAMPMENT',
  'DISTRICT_HARBOR',
  'DISTRICT_COMMERCIAL_HUB',
  'DISTRICT_ENTERTAINMENT_COMPLEX',
  'DISTRICT_THEATER',
  'DISTRICT_INDUSTRIAL_ZONE',
  'DISTRICT_GOVERNMENT',
  'DISTRICT_AQUEDUCT',
  'DISTRICT_WONDER',
  'DISTRICT_NEIGHBORHOOD',
  'DISTRICT_SPACEPORT',
  'DISTRICT_AERODROME',
  'DISTRICT_PRESERVE',
  'DISTRICT_DIPLOMATIC_QUARTER',
  'DISTRICT_CANAL',
  'DISTRICT_DAM',
  'DISTRICT_WATER_ENTERTAINMENT_COMPLEX',
  'IMPROVEMENT_FARM',
  'IMPROVEMENT_MINE',
  'IMPROVEMENT_QUARRY',
  'IMPROVEMENT_CAMP',
  'IMPROVEMENT_PASTURE',
  'IMPROVEMENT_PLANTATION',
  'IMPROVEMENT_FISHING_BOATS',
  'IMPROVEMENT_LUMBER_MILL',
  'IMPROVEMENT_FORT',
  'IMPROVEMENT_OIL_WELL',
  'IMPROVEMENT_SEASIDE_RESORT',
  'GOVERNOR_THE_AMBASSADOR',
  'GOVERNOR_THE_BUILDER',
  'GOVERNOR_THE_CARDINAL',
  'GOVERNOR_THE_DEFENDER',
  'GOVERNOR_THE_EDUCATOR',
  'GOVERNOR_THE_MERCHANT',
  'GOVERNOR_THE_RESOURCE_MANAGER',
  'GOVERNOR_IBRAHIM',
  'GOVERNOR_PROMOTION_BUILDER_GUILDMASTER',
  'GOVERNOR_PROMOTION_CARDINAL_BISHOP',
  'GOVERNOR_PROMOTION_DEFENSE_LOGISTICS',
  'GOVERNOR_PROMOTION_EDUCATOR_CONNOISSEUR',
  'GOVERNOR_PROMOTION_EDUCATOR_GRANTS',
  'GOVERNOR_PROMOTION_MERCHANT_CONTRACTOR',
  'GOVERNOR_PROMOTION_RESOURCE_MANAGER_GROUNDBREAKER',
  'GOVERNOR_PROMOTION_RESOURCE_MANAGER_SURPLUS_LOGISTICS',
  'GOVERNOR_PROMOTION_ZONING_COMMISSIONER',
  'BBG_AGRICULTURE_PROMOTION',
  'GOVERNOR_PROMOTION_EDUCATOR_LIBRARIAN',
  'GOVERNOR_PROMOTION_WATER_WORKS',
  'GOVERNOR_PROMOTION_EDUCATOR_RESEARCHER',
  'GOVERNOR_PROMOTION_MERCHANT_LAND_ACQUISITION',
  'GOVERNOR_PROMOTION_RESOURCE_MANAGER_INDUSTRIALIST',
  'GOVERNOR_PROMOTION_RESOURCE_MANAGER_BLACK_MARKETEER',
  'GOVERNOR_PROMOTION_RESOURCE_MANAGER_VERTICAL_INTEGRATION',
  'GOVERNOR_PROMOTION_AMBASSADOR_MESSENGER',
  'GOVERNOR_PROMOTION_AMBASSADOR_AFFLUENCE',
  'UNITOPERATION_MOVE_TO',
  'UNITOPERATION_SPY_TRAVEL_NEW_CITY',
  'UNITOPERATION_MAKE_TRADE_ROUTE',
  'UNITOPERATION_AUTOMATE_EXPLORE',
  'UNITOPERATION_RANGE_ATTACK',
  'UNITOPERATION_BUILD_IMPROVEMENT',
  'UNITOPERATION_SPY_COUNTERSPY',
  'UNITOPERATION_PILLAGE',
  'UNITOPERATION_SWAP_UNITS',
  'UNITOPERATION_COASTAL_RAID',
  'UNITOPERATION_TELEPORT_TO',
  'UNITOPERATION_REPAIR',
  'UNITOPERATION_AIR_ATTACK',
  'UNITOPERATION_BUILD_ROUTE',
  'UNITOPERATION_TOURISM_BOMB',
  'UNITOPERATION_WMD_STRIKE',
] as const

export interface HashResolver {
  sources: string[]
  typesDbPath?: string | null
  resolve(hash: number): string | null
  resolveOrHash(hash: number): string
  entries(): Array<[number, string]>
}

export interface CreateHashResolverOptions {
  typesDbPath?: string | null
  loadDefaultTypesDb?: boolean
}

export function crc32(value: Uint8Array | string): number {
  const bytes = typeof value === 'string' ? new TextEncoder().encode(value) : value
  let crc = 0xFFFFFFFF
  for (const byte of bytes) crc = CRC32_TABLE[(crc ^ byte) & 0xFF]! ^ (crc >>> 8)
  return (crc ^ 0xFFFFFFFF) >>> 0
}

export function civHash(type: string): number {
  return (~crc32(type)) >>> 0
}

export function resolveCoreType(hash: number): string | null {
  return CORE_TYPE_NAMES.get(hash) ?? null
}

export function resolveCivReplayDedicationDisplayName(hash: number): string | null {
  return CIV_REPLAY_DEDICATION_DISPLAY_NAMES_BY_HASH.get(hash) ?? null
}

export function createHashResolver(options: CreateHashResolverOptions = {}): HashResolver {
  const names = new Map<number, string>()
  const sources: string[] = []
  let typesDbPath: string | null = null

  addTypes(names, STATIC_TYPE_NAMES)
  sources.push('static-core')

  const dbPath = options.typesDbPath ?? (options.loadDefaultTypesDb === false ? null : findDefaultTypesDbPath())
  if (dbPath && existsSync(dbPath)) {
    try {
      const loaded = loadTypesFromSqlite(dbPath)
      addTypes(names, loaded)
      sources.push(dbPath)
      typesDbPath = dbPath
    }
    catch {
      sources.push(`${dbPath} (failed)`)
    }
  }

  return {
    sources,
    typesDbPath,
    resolve(hash: number) {
      return names.get(hash) ?? null
    },
    resolveOrHash(hash: number) {
      return names.get(hash) ?? formatHash(hash)
    },
    entries() {
      return [...names.entries()].sort((left, right) => left[0] - right[0])
    },
  }
}

export function formatHash(hash: number): string {
  return `0x${hash.toString(16).padStart(8, '0')}`
}

function createCrc32Table(): Uint32Array {
  const table = new Uint32Array(256)
  for (let index = 0; index < table.length; index += 1) {
    let crc = index
    for (let bit = 0; bit < 8; bit += 1) crc = crc & 1 ? 0xEDB88320 ^ (crc >>> 1) : crc >>> 1
    table[index] = crc >>> 0
  }
  return table
}

function addTypes(names: Map<number, string>, types: Iterable<string>) {
  for (const type of types) names.set(civHash(type), type)
}

function findDefaultTypesDbPath(): string | null {
  const localAppData = process.env.LOCALAPPDATA
  if (!localAppData) return null
  return join(localAppData, 'Firaxis Games', 'Sid Meier\'s Civilization VI', 'Cache', 'DebugGameplay.sqlite')
}

function loadTypesFromSqlite(dbPath: string): string[] {
  const db = new Database(dbPath, { readonly: true })
  try {
    const rows = db.query<{ Type: string }, []>('select Type from Types where Type is not null').all()
    return rows.map(row => row.Type).filter(type => type.length > 0)
  }
  finally {
    db.close()
  }
}
